region             = "us-west-2"
registry_name      = "features-api-registry"
env                = "dev"
project_name       = "veda-features-api"
db_public_subnet = false
availability_zones = ["us-west-2a", "us-west-2b"]
service_port       = 8080
dns_zone_name      = "delta-backend.com"
dns_subdomain      = "ghg-dev"
tags               = {"project": "veda", "service": "veda-features-api-dev"}
vpc_id = "vpc-0512162c42da5e645"
