region             = "us-west-2"
registry_name      = "ghgc-features-api-registry"
env                = "dev"
project_name       = "ghgc-features-api"
availability_zones = ["us-west-2a", "us-west-2b"]
service_port       = "8080"
dns_zone_name      = "dev.ghg.center"
tags               = {"project": "ghgc", "service": "ghgc-features-api-dev"}
vpc_id = "vpc-0a20167ff1004d0f2"
