name: Deploy
inputs:
  env_aws_secret_name:
    required: true
    type: string
  env-file:
    type: string
    default: ".env"
  dir:
    required: false
    type: string
    default: "."
  script_path:
    type: string

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install python dependencies
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install boto3

    - name: Get relevant environment configuration from aws secrets
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        if [[ -z "${{ inputs.script_path }}" ]]; then
        ./scripts/sync-env.sh ${{ inputs.env_aws_secret_name }}
        else
        python ${{ inputs.script_path }} --secret-id ${{ inputs.env_aws_secret_name }}
        source ${{ inputs.env-file }}
        echo "PREFIX=feature-api-${STAGE}" >> ${{ inputs.env-file }}
        echo "REGISTRY_NAME=feature-api-${STAGE}" >> ${{ inputs.env-file }}
        echo "ENV=${STAGE}" >> ${{ inputs.env-file }}
        echo "PROJECT_NAME=veda-${STAGE}" >> ${{ inputs.env-file }}
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.9

    - name: Deploy
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        bash ./scripts/deploy.sh .env <<< init
        bash ./scripts/deploy.sh .env <<< deploy

